### PR TITLE
Toggle label of "Cancel" button when configuring the effect

### PR DESCRIPTION
**Pull request by jamesrkiger**
This PR fixes issue #47. At the same time, it also changes the handling of identity state so that `identity.mirror_settings` is updated upon a successful save. It is not the most graceful means of doing this. I would have preferred to use the refetch() function from RA's useGetIdentity(), but I could not get this to work and wasn't sure if I should be spending much time on it.

I believe the identity state change fixes an issue that I **think** was impacting the function of the "Profile values" button. My assumption was that the "Profile values" button was intended to reset the mirror settings to their last saved values. For example:

1. My original settings are the same as the default settings. Default value for `position.x` is 0.
2. I open the mirror app and change `position.x` to 1 and press 'Save'.
3. I change `position.x` to 2 without saving.
4. I press the "Profile values" button

I expect that when I press "Profile values" `position.x` should revert back to 1, its last saved value. If I'm correct in this, the button was not working as intended because the identity state was not updated upon pressing save. Instead, `position.x` would revert to 0, the saved value when the mirror app was initially loaded. Please let me know if I misunderstood this.

### CODE REVIEW

**Comment by noliveleger** [comment]
@jamesrkiger , you did understand correctly. "Default values" would have reset `position.x` to 0. 

After testing the feature a little more, I think the flow is not super user-friendly. Actually I would like to get something similar to rest of the app (and RA behaviour), e.g.: 

- The `Save` button should be gray out until something has changed. (it's not possible to save if nothing has changed).
- The `Close` button should be gray, not blue (Look at back/cancel button on other pages)

Screenshot 2023-10-31 at 09 30 52

- I'm gonna change my mind (sorry about that), the `Close` button label should stay `Close` all time (no toggle anymore) but a confirm dialog should appear to confirm the user really wants to quit without saving. (The same behaviour as `Cancel` button on edit pages)

**Review by noliveleger — CHANGES_REQUESTED** [review]
[See my comment above](https://github.com/mirror-effect-plus-protocol/mepp-web/pull/48#issuecomment-1787230063)

**Comment by noliveleger** [comment]
@jamesrkiger. Seems great except for the confirm window.
Let's use MUI Dialog instead to be consistent with the rest of the app. 

Something like that.
Screenshot 2023-11-02 at 12 08 03

**Comment by jamesrkiger** [comment]
@noliveleger Regarding the confirmation, I wasn't sure what you had in mind so I put the window confirmation there as a quick fix. I don't think that using the React Admin Material confirmation is going to be a quick task, though. The actual mirror interface (along with the login page, for example), are separate from React Admin. They don't use the RA themes, layout wrappers, etc. So we would need to either change that (and I'm assuming there's a reason it was built separately to begin with) or design a custom modal to copy the style of RA modal. I'm happy to look into this, but I thought I should check with you first before spending a significant amount of time on it.

**Comment by noliveleger** [comment]
@jamesrkiger , that's what I thought. 
Please hold on, I'll ask our React guru @fperreault.

**Comment by fperreault** [comment]
@noliveleger I added confirmation modal like that:

Capture d’écran, le 2023-11-21 à 16 58 52

Before you asking ;) No transparency background can be applied, because I reused the Overlay used everywhere(proflie/language settings). And this Overlay has an opaque background.

**Comment by noliveleger** [comment]
No need for background transparency. 
LGTM

**Pull request merged**
